### ISSUE TITLE
CI/CD 구현

### ISSUE THREAD

**Issue by tangjinlog** [myeonjeobeottae/client#22]
# Feature
- `main` 브랜치에 코드 변경이 일어나면 자동으로 EC2 서버에 배포된다.

# Description
- **workflows**
  - `feature-example` -> `main` merge
  -  `github-actions` 감지
  -  `Docker Image build` -> `DockerHub Push`
  - `EC2 접속` 및 `docker-compose`로 컨테이너 실행
  - **배포 완료**

# To do list
- [ ] `github-actions.yml` 작성
- [x] `docker-compose.yml`에서 DockerHub Image를 pull 받도록 수정 

# Troubleshooting
-  ✅  Nginx-proxy-manager 폴더의 permission denied 현상 https://github.com/myeonjeobeottae/client/issues/22#issuecomment-1879671639
-  ✅  github-actions 중, DockerFile 못 찾는 현상 https://github.com/myeonjeobeottae/client/issues/22#issuecomment-1879686242
-  ✅  Docker Image를 Hub에 Push하고 Pull 받았는데, 최신 코드가 배포 반영이 안되는 현상 https://github.com/myeonjeobeottae/client/issues/22#issuecomment-1879684985

**Comment by tangjinlog** [comment]
## Nginx-proxy-manager 폴더의 permission denied

|&nbsp;구분&nbsp;| ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ설명 ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ|
| :-----------: | ------------ |
| 현상 |  github-actions 중, **nginx-proxy-manager**가 권한없음으로 열리지 않음 |
| 원인 | nginx-proxy-manager 폴더의 권한이 현재 사용자와 일치하지 않을 때 발생 |
| 해결책 | `ls -ld nginx-proxy-manager`로 폴더의 권한정보를 먼저 확인한다.<br> 당시 사용자와 사용자 그룹이 **root**로 설정되어 있었음.<br>현재 EC2 접속 사용자는 **ubuntu**이기 때문에, 권한설정을 바꿔줘야 한다.<br><br>`chown -R ubuntu:ubuntu nginx-proxy-manager`<br><img width="511" alt="image" src="https://github.com/myeonjeobeottae/client/assets/96574345/83f6f4e0-e26d-43b1-8df9-e7358a90e94e"> |

**Comment by tangjinlog** [comment]
## Docker Image를 Hub에 Push하고 Pull 받았는데, 최신 코드가 배포 반영이 안되는 현상

- 기존 github-actions 코드
```yml
#.github/workflows/github-actions.yml 

# github repository actions 페이지에 나타날 이름
name: CI/CD using github actions & docker
# event trigger
# main 브랜치에 push가 되었을 때 실행
on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      # github 가상환경에서 작업할 수 있도록 repository 코드 복제
      - uses: actions/checkout@v3

      # docker build & push to production
      - name: Docker build & push to prodction
        if: contains(github.ref, 'main')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
          docker-compose build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME}}/myeonjeobeottae .
          docker push ${{ secrets.DOCKER_USERNAME}}/myeonjeobeottae

      # deploy to production
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_KEY}}
          envs: GITHUB_SHA
          script: |
            cd client/
            sudo su
            docker-compose down
            docker-compose up -d --build
            docker system prune -f
```

- 기존 EC2 docker-compose.yml 코드
```yml
# docker 컨테이너 버전을 명시
version: '3.8'

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - 81:81 #관리포트
      - 80:80 #http
      - 443:443 #https
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    environment:
      DISABLE_IPV6: 'true'
    depends_on:
      - myeonjeobeottae

  myeonjeobeottae:
    container_name: myeonjeobeottae
    # 현재 경로에 이미지 빌드
    build:
      context: .
      dockerfile: Dockerfile.yml
    ports:
      - '3000:3000'
    image: tanglog/test:0.0.1
```
`github-actions`에서 EC2에 접속한 후, docker-compose up -d --build로 컨테이너를 실행시키고 있는데,<br>EC2의 `docker-compose.yml`에서는 다시 이미지 build를 하고있다.<br><br>그래서 github-actions의 과정에서 이미지를 build하고 DockerHub에 push했음에도 만들어진 이미지를 사용하지 않고 있었던 것.<br>그래서 만들어진 image를 pull하는 코드로 변경하면서 문제를 해결할 수 있었다.<br>
- 변경 후 EC2 docker-compose.yml 코드
```yml
# docker-compose.yml
...
myeonjeobeottae:
    container_name: myeonjeobeottae
    image: tanglog/myeonjeobeottae:latest
    ports:
      - '3000:3000'
```

docker build의 개념을 잘못 이해해서 일어난 일이었다.
docker-compose.yml에서 nginx이미지는 Hub에서 받아오고, 면접어때 app 소스코드는 build하고 있었기 때문에,
docker-compose build 명령어로 이미지를 만들면 두가지 컨테이너가 하나의 이미지에 담기는 줄 알았는데 아니였다.
docker 이미지는 단일 컨테이너만 담을 수 있다고 한다.
결과적으로 nginx 와 면접어때 두 가지 이미지를 DockerHub에서 pull 받아오고 그걸 docker-compose up으로 한 번에 실행시켜야 하는 것이다.

CI/CD 구축하고 난 후 EC2안에서 clone을 안받아도 되니, 구조가 매우 깔끔해져서 만족한다!
<img width="237" alt="image" src="https://github.com/myeonjeobeottae/client/assets/96574345/90d8ffda-37ac-4158-b3aa-652f870f31f7">
기존 src를 비롯한 각종 config 파일들을 제거하고, nginx 폴더와 docker-compose.yml, env 파일만으로 배포할 수 있게 되었다.
